// Generated by CoffeeScript 1.3.3
(function() {
  var ArrayField, RefField, TextField;

  TextField = (function() {

    function TextField(length, default_value) {
      this.type = 'text';
      this.length = length;
      this.default_value = default_value != null ? default_value : '';
    }

    return TextField;

  })();

  module.exports.TextField = TextField;

  ArrayField = (function() {

    function ArrayField(item_template_name) {
      this.type = 'array';
      this.item_template_name = item_template_name;
      this.default_value = [];
    }

    return ArrayField;

  })();

  module.exports.ArrayField = ArrayField;

  RefField = (function() {

    function RefField(item_template_name) {
      this.type = 'ref';
      this.item_template_name = item_template_name;
      this.default_value = {};
    }

    return RefField;

  })();

  module.exports.RefField = RefField;

}).call(this);
