// Generated by CoffeeScript 1.3.3
(function() {
  var forms, get_form, landing_page, m, maker, post_form, table, tables, user,
    _this = this;

  maker = require('./maker.js');

  tables = {
    users: {
      name: 'users',
      type: 'user',
      list_def: {
        __list_fields: ['name', 'surname']
      },
      data: [],
      form: 'user'
    }
  };

  forms = {
    user: {
      type: 'user'
    }
  };

  user = {
    name: new maker.TextField(30),
    surname: new maker.TextField(50)
  };

  m = new maker.Maker;

  m.register_template('user', user);

  tables.users.data = m.convert([
    {
      name: 'johan',
      surname: 'jordaan'
    }, {
      name: 'lorraine',
      surname: 'evert'
    }
  ]).to('user');

  post_form = function(req, res) {
    console.log('Posting stuff');
    return res.render('noxious/index', {
      title: 'noxious'
    });
  };

  get_form = function(req, res) {
    var form, form_name;
    form_name = req.params.form;
    form = forms[form_name];
    if (req.xhr) {
      return res.partial('noxious/form', {
        form: form
      });
    } else {
      return res.render('noxious/form', {
        form: form
      });
    }
  };

  landing_page = function(req, res) {
    return res.render('noxious/index', {
      title: 'noxious'
    });
  };

  table = function(req, res) {
    var table_name;
    table_name = req.params.table;
    table = tables[table_name];
    if (req.xhr) {
      return res.partial('noxious/table', {
        table: table
      });
    } else {
      return res.render('noxious/table', {
        table: table
      });
    }
  };

  module.exports = function(app) {
    app.get('/noxious', landing_page);
    app.get('/noxious/table/:table', table);
    app.get('/noxious/form/:form', get_form);
    return app.post('/noxious/form', post_form);
  };

}).call(this);
