// Generated by CoffeeScript 1.3.3
(function() {
  var clear, construct_class, construct_class_field, construct_classes_from_dir, construct_classes_from_file, constructed_artifacts, fs, init, path,
    _this = this;

  fs = require('fs');

  path = require('path');

  constructed_artifacts = [];

  clear = function() {
    var cls, _i, _len;
    for (_i = 0, _len = constructed_artifacts.length; _i < _len; _i++) {
      cls = constructed_artifacts[_i];
      delete module.exports[cls];
    }
    return constructed_artifacts = [];
  };

  construct_class_field = function(cls, key, field) {
    var _ref;
    if (field.type === 'text') {
      cls[key] = (_ref = field.default_value) != null ? _ref : '';
    }
    if (field.type === 'ref') {
      return cls[key] = new module.exports[field.item_template_name];
    }
  };

  construct_class = function(default_name, template) {
    var name, plural, template_instance, _ref, _ref1;
    template_instance = new template;
    name = (_ref = template_instance.__name) != null ? _ref : default_name;
    plural = (_ref1 = template_instance.__plural) != null ? _ref1 : name + 's';
    constructed_artifacts.push(name);
    module.exports[name] = function() {
      var key, _i, _len, _ref2,
        _this = this;
      _ref2 = Object.keys(template_instance);
      for (_i = 0, _len = _ref2.length; _i < _len; _i++) {
        key = _ref2[_i];
        construct_class_field(this, key, template_instance[key]);
      }
      this.save = function() {
        return console.log('Saving ...');
      };
      return void 0;
    };
    constructed_artifacts.push(plural);
    return module.exports[plural] = {
      load: function() {
        return console.log('Loading ...');
      }
    };
  };

  construct_classes_from_file = function(file) {
    var key, tmp, _i, _len, _ref, _results;
    tmp = require(file);
    _ref = Object.keys(tmp);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      key = _ref[_i];
      _results.push(construct_class(key, tmp[key]));
    }
    return _results;
  };

  construct_classes_from_dir = function(dir) {
    var file, _i, _len, _ref, _results;
    _ref = fs.readdirSync(dir);
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      file = _ref[_i];
      _results.push(construct_classes_from_file(path.join(dir, file)));
    }
    return _results;
  };

  init = function(settings) {
    var dir, _i, _len, _ref, _results;
    _ref = settings.template_dirs;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      dir = _ref[_i];
      _results.push(construct_classes_from_dir(path.join(settings.root_dir, dir)));
    }
    return _results;
  };

  module.exports.clear = clear;

  module.exports.construct_class = construct_class;

  module.exports.init = init;

}).call(this);
